
---

### **`netlify.toml`**
Den här filen konfigurerar din Netlify-deployment:

```toml
[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
